// Generated by CoffeeScript 1.6.3
(function() {
  var express, metaserve, setup_app;

  express = require('express');

  metaserve = require('metaserve');

  setup_app = function(config) {
    var app;
    app = express();
    app.set('views', config.view_dir || './views');
    app.set('view engine', config.view_engine || 'jade');
    app.use(function(req, res, next) {
      console.log("[" + req.method + "] " + req.url);
      return next();
    });
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(app.router);
    app.use(metaserve(config.static_dir || './static'));
    app.start = function() {
      return app.listen(config.port, function() {
        return console.log("Listening on :" + config.port);
      });
    };
    return app;
  };

  module.exports = {
    setup_app: setup_app
  };

}).call(this);
