// Generated by CoffeeScript 1.10.0
(function() {
  var express, merge_all, merge_objs, metaserve, setup,
    slice = [].slice;

  express = require('express');

  metaserve = require('metaserve');

  merge_objs = function(o1, o2) {
    var k, v;
    for (k in o2) {
      v = o2[k];
      o1[k] = v;
    }
    return o1;
  };

  merge_all = function(objs) {
    var i, len, o, oa;
    oa = {};
    for (i = 0, len = objs.length; i < len; i++) {
      o = objs[i];
      merge_objs(oa, o);
    }
    return oa;
  };

  setup = function() {
    var RedisStore, app, config, configs, i, len, middleware, ref, ref1, ref2;
    configs = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    config = merge_all(configs);
    app = config.app || express();
    if (config.app) {
      app = config.app;
      delete config.app;
    }
    app.config = config;
    app.set('views', config.view_dir || './views');
    app.set('view engine', config.view_engine || 'jade');
    app.use(function(req, res, next) {
      console.log("[" + (new Date().toISOString()) + "] " + req.method + " " + req.url);
      return next();
    });
    if (!config.no_cookie_parser) {
      app.use(express.cookieParser());
    }
    if (!config.no_body_parser) {
      app.use(express.bodyParser());
    }
    if (config.session != null) {
      RedisStore = require('connect-redis')(express);
      app.use(express.session(merge_objs({
        store: new RedisStore({
          host: ((ref = config.redis) != null ? ref.host : void 0) || 'localhost'
        })
      }, config.session)));
    }
    if (config.middleware != null) {
      ref1 = config.middleware;
      for (i = 0, len = ref1.length; i < len; i++) {
        middleware = ref1[i];
        app.use(middleware);
      }
    }
    app.use(app.router);
    app.use(metaserve(config.metaserve || config.static_dir || {
      compilers: {
        css: [
          !config.debug ? require('metaserve-bouncer')({
            ext: 'bounced.css'
          }) : void 0, require('metaserve-css-styl')()
        ],
        js: [
          !config.debug ? require('metaserve-bouncer')({
            ext: 'bounced.js'
          }) : void 0, require('metaserve-js-coffee-reactify')({
            ext: 'coffee',
            uglify: !config.debug
          })
        ]
      }
    }));
    if ((ref2 = config.using) != null) {
      ref2.map(function(using) {
        return app.use(using);
      });
    }
    app.use(config.fallback || function(req, res, next) {
      return res.send(404, "Could not find page.");
    });
    app.start = function() {
      return app.listen(config.port, function() {
        return console.log("Listening on :" + config.port);
      });
    };
    return app;
  };

  module.exports = setup;

}).call(this);
