// Generated by CoffeeScript 1.10.0
(function() {
  var express, merge_objs, metaserve, setup,
    slice = [].slice;

  express = require('express');

  metaserve = require('metaserve');

  merge_objs = function(objs) {
    var i, k, len, o, obj, v;
    o = {};
    for (i = 0, len = objs.length; i < len; i++) {
      obj = objs[i];
      for (k in obj) {
        v = obj[k];
        o[k] = v;
      }
    }
    return o;
  };

  setup = function() {
    var RedisStore, app, config, configs, i, len, middleware, ref, ref1;
    configs = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    config = merge_objs(configs);
    app = config.app || express();
    if (config.app) {
      app = config.app;
      delete config.app;
    }
    app.config = config;
    app.set('views', config.view_dir || './views');
    app.set('view engine', config.view_engine || 'jade');
    app.use(function(req, res, next) {
      console.log("[" + (new Date().toISOString()) + "] " + req.method + " " + req.url);
      return next();
    });
    if (!config.no_cookie_parser) {
      app.use(express.cookieParser());
    }
    if (!config.no_body_parser) {
      app.use(express.bodyParser());
    }
    if (config.use_sessions != null) {
      RedisStore = require('connect-redis')(express);
      app.use(express.session({
        store: new RedisStore({
          host: ((ref = config.redis) != null ? ref.host : void 0) || 'localhost'
        }),
        secret: config.session_secret
      }));
    }
    if (config.middleware != null) {
      ref1 = config.middleware;
      for (i = 0, len = ref1.length; i < len; i++) {
        middleware = ref1[i];
        app.use(middleware);
      }
    }
    app.use(app.router);
    app.use(metaserve(config.metaserve || config.static_dir || {
      compilers: {
        css: [
          !config.debug ? require('metaserve-bouncer')({
            ext: 'bounced.css'
          }) : void 0, require('metaserve-css-styl')()
        ],
        js: [
          !config.debug ? require('metaserve-bouncer')({
            ext: 'bounced.js'
          }) : void 0, require('metaserve-js-coffee-reactify')({
            ext: 'coffee',
            uglify: !config.debug
          })
        ]
      }
    }));
    app.start = function() {
      return app.listen(config.port, function() {
        return console.log("Listening on :" + config.port);
      });
    };
    return app;
  };

  module.exports = setup;

}).call(this);
