// Generated by CoffeeScript 1.8.0
(function() {
  var merge_all, merge_objs;

  merge_objs = function(o1, o2) {
    var k, v;
    for (k in o2) {
      v = o2[k];
      if (typeof o1[k] === 'object') {
        merge_objs(o1[k], v);
      } else {
        o1[k] = v;
      }
    }
    return o1;
  };

  merge_all = function(objs) {
    var o, oa, _i, _len;
    oa = {};
    for (_i = 0, _len = objs.length; _i < _len; _i++) {
      o = objs[_i];
      merge_objs(oa, o);
    }
    return oa;
  };

  module.exports = {
    merge_objs: merge_objs,
    merge_all: merge_all
  };

}).call(this);
