// Generated by CoffeeScript 1.10.0
(function() {
  var merge_all, merge_objs;

  merge_objs = function(o1, o2) {
    var k, v;
    for (k in o2) {
      v = o2[k];
      o1[k] = v;
    }
    return o1;
  };

  merge_all = function(objs) {
    var i, len, o, oa;
    oa = {};
    for (i = 0, len = objs.length; i < len; i++) {
      o = objs[i];
      merge_objs(oa, o);
    }
    return oa;
  };

  module.exports = {
    merge_objs: merge_objs,
    merge_all: merge_all
  };

}).call(this);
